### ISSUE TITLE
Remarques sur cluster.stop

### ISSUE THREAD

**Issue by ylorenza** [voyages-sncf-technologies/maze#9]
Salut,

Je m'interroge sur l'amélioration et le renommage de cette méthode.
Pour le contexte, je le post en dessous

```
  def stop(): Unit = {
    nodes.foreach(_.clear())
  }

```

- On a un cluster stop qui finalement détruis complètement le cluster (voir scaladoc de la méthode clear) alors qu'un node.stop peut etre restarté. Il faudrait peut être renommer la fonction en destroy.

- On invalide pas completement l'objet et on garde les object nodes lors d'un cluster.stop. Du coup si tu as une erreur dans un before, dans ton after, tu as gardé les references d'avant et c'est pas simple a debug. On pourrait nettoyer la liste des nodes et / ou avoir un bool isDestroy.

Moi j'ai fixé  le pb dans mon code avec un élégant 
```
  injectors = null
    clients = null
    cluster = null 
```
Et je sais bien que le vrai probleme est dans le before  et que c'est liée a docker

Mais je me dis qu'on pourrait faire en sorte que maze soit plus résilient de base a ce genre de chose

Ton avis ?

**Comment by larochef** [comment]
Sur le premier point du stop qui appelle clear et fait pas très intuitif, je suis plutôt daccord, même si je trouve un peu gênant d'avoir un start de pas de stop ;) De plus, nous n'avons jamais vraiment eu le besoin de stopper tous les noeuds d'un cluster donné.


Pour le deuxième problème, j'ai du mal à capter, théoriquement, chaque before réinstancie une nouvelle instance du cluster et, de fait, il ne devrait pas y avoir de mic-mac entre deux tests.

**Comment by garnaud** [comment]
On pas reprendre la même sémantique que docker compose ? (De tête up, down,
remove...)


Le 3 févr. 2017 5:51 PM, "larochef" <notifications@github.com> a écrit :

Sur le premier point du stop qui appelle clear et fait pas très intuitif,
je suis plutôt daccord, même si je trouve un peu gênant d'avoir un start de
pas de stop ;) De plus, nous n'avons jamais vraiment eu le besoin de
stopper tous les noeuds d'un cluster donné.

Pour le deuxième problème, j'ai du mal à capter, théoriquement, chaque
before réinstancie une nouvelle instance du cluster et, de fait, il ne
devrait pas y avoir de mic-mac entre deux tests.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/voyages-sncf-technologies/maze/issues/9#issuecomment-277299783>,
or mute the thread

**Comment by ylorenza** [comment]
Pour le deuxième point, c'est quand tu as plusieurs cluster en parallèle (ex redis et injecteur)

tu fais un stop complet qui marche
un start du cluster qui plante, et tu arrive dans le after avec tes injecteur qui sont deja plus bon

**Comment by larochef** [comment]
Ce que tu peux faire c'est de réinstancier tous les clusters en début de before pour éviter ça alors.
Tu commence par tous les new, puis tu refais tout dans le bon ordre.


Sinon, une autre chose simple serait de vider la liste des noeuds lors du stop du cluster, vu que ces noeuds ne correspondent à plus rien.

**Comment by ylorenza** [comment]
Moi ça va de vider la liste des noeuds. Je vois que tu l'a deja fais. Merci
